// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: password.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ForgotPasswordData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ForgotPasswordData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForgotPasswordData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ForgotPasswordDataMultiError, or nil if none found.
func (m *ForgotPasswordData) ValidateAll() error {
	return m.validate(true)
}

func (m *ForgotPasswordData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	if len(errors) > 0 {
		return ForgotPasswordDataMultiError(errors)
	}
	return nil
}

// ForgotPasswordDataMultiError is an error wrapping multiple validation errors
// returned by ForgotPasswordData.ValidateAll() if the designated constraints
// aren't met.
type ForgotPasswordDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForgotPasswordDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForgotPasswordDataMultiError) AllErrors() []error { return m }

// ForgotPasswordDataValidationError is the validation error returned by
// ForgotPasswordData.Validate if the designated constraints aren't met.
type ForgotPasswordDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForgotPasswordDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForgotPasswordDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForgotPasswordDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForgotPasswordDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForgotPasswordDataValidationError) ErrorName() string {
	return "ForgotPasswordDataValidationError"
}

// Error satisfies the builtin error interface
func (e ForgotPasswordDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForgotPasswordData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForgotPasswordDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForgotPasswordDataValidationError{}

// Validate checks the field values on RestPasswordToken with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RestPasswordToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RestPasswordToken with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RestPasswordTokenMultiError, or nil if none found.
func (m *RestPasswordToken) ValidateAll() error {
	return m.validate(true)
}

func (m *RestPasswordToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IssuedTo

	// no validation rules for IssuedOn

	// no validation rules for ExpiresOn

	// no validation rules for Token

	if len(errors) > 0 {
		return RestPasswordTokenMultiError(errors)
	}
	return nil
}

// RestPasswordTokenMultiError is an error wrapping multiple validation errors
// returned by RestPasswordToken.ValidateAll() if the designated constraints
// aren't met.
type RestPasswordTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RestPasswordTokenMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RestPasswordTokenMultiError) AllErrors() []error { return m }

// RestPasswordTokenValidationError is the validation error returned by
// RestPasswordToken.Validate if the designated constraints aren't met.
type RestPasswordTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RestPasswordTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RestPasswordTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RestPasswordTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RestPasswordTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RestPasswordTokenValidationError) ErrorName() string {
	return "RestPasswordTokenValidationError"
}

// Error satisfies the builtin error interface
func (e RestPasswordTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRestPasswordToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RestPasswordTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RestPasswordTokenValidationError{}

// Validate checks the field values on ResetPasswordData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ResetPasswordData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetPasswordData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetPasswordDataMultiError, or nil if none found.
func (m *ResetPasswordData) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetPasswordData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for NewPassword

	// no validation rules for ConfirmPassword

	// no validation rules for UserId

	if len(errors) > 0 {
		return ResetPasswordDataMultiError(errors)
	}
	return nil
}

// ResetPasswordDataMultiError is an error wrapping multiple validation errors
// returned by ResetPasswordData.ValidateAll() if the designated constraints
// aren't met.
type ResetPasswordDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetPasswordDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetPasswordDataMultiError) AllErrors() []error { return m }

// ResetPasswordDataValidationError is the validation error returned by
// ResetPasswordData.Validate if the designated constraints aren't met.
type ResetPasswordDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetPasswordDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetPasswordDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetPasswordDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetPasswordDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetPasswordDataValidationError) ErrorName() string {
	return "ResetPasswordDataValidationError"
}

// Error satisfies the builtin error interface
func (e ResetPasswordDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetPasswordData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetPasswordDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetPasswordDataValidationError{}
